apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kbot-temp
  name: kbot-temp
  namespace: test
spec:
  containers:
  - image: ghcr.io/vvadymv/kbot:v1.1.1-3a0f514-linux-amd64
    name: kbot-temp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
